services:
  matrix-app:
    build: .
    ports:
      - "3000:3000"  # Next.js frontend
      - "3001:3001"  # Socket.IO server
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
